// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID           pgtype.UUID      `json:"id"`
	CreatedAt    pgtype.Timestamp `json:"-"`
	UpdatedAt    pgtype.Timestamp `json:"-"`
	Name         string           `json:"name" validate:"required,min=4,max=200"`
	Amount       int16            `json:"amount" validate:"required,min=1"`
	Carbohydrate int16            `json:"carbohydrate"`
	Protein      int16            `json:"protein"`
	Fat          int16            `json:"fat"`
	UserID       pgtype.UUID      `json:"-"`
}

type Report struct {
	ID                 pgtype.UUID `json:"id"`
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	Date               pgtype.Date    `json:"date"`
	AmoutOfEntries     int16          `json:"numberOfEntries"`
	CarbohydratesTotal pgtype.Numeric `json:"carbohydratesTotal"`
	ProteinsTotal      pgtype.Numeric `json:"proteinsTotal"`
	FatsTotal          pgtype.Numeric `json:"fatsTotal"`
	UserID             pgtype.UUID
}

type ReportEntry struct {
	ID            pgtype.UUID `json:"id"`
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	Amount        int16          `json:"amount" validate:"required,min=0"`
	Carbohydrates pgtype.Numeric `json:"carbohydrates" validate:"required,min=0"`
	Proteins      pgtype.Numeric `json:"proteins" validate:"required,min=0"`
	Fats          pgtype.Numeric `json:"fats" validate:"required,min=0"`
	ProductID     pgtype.UUID    `json:"productId" validate:"required,uuid4"`
	ReportID      pgtype.UUID    `json:"reportId" validate:"uuid4"`
}

type User struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	LastLogin   pgtype.Timestamp
	Name        string
	Email       string
	PhoneNumber string
}

type Vault struct {
	UserID   pgtype.UUID
	HashedPw string
	Active   bool
}
